package edu.sliit.document;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * This class represents the Bin document that will be stored in MongoDB.
 * It includes details such as the bin's ID, user information, type, capacity, and location.
 */
@Setter
@Getter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "Bin_Details")
public class Bin {

    /**
     * Unique identifier for each bin document (automatically generated by MongoDB).
     */
    @Id
    private String id;

    /**
     * Unique bin identifier.
     * Indexed to ensure that each bin has a unique identifier.
     */
    @Indexed(unique = true)
    private String  BinId;

    /**
     * ID of the user who owns the bin.
     */
    private String userId;

    /**
     * The type of the bin (e.g., recycling, general waste).
     */
    private String binType;

    /**
     * The capacity of the bin.
     */
    private String  capacity;

    /**
     * The location where the bin is placed.
     */
    private String location;

    private String Status;


}
