package edu.sliit.document;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

/**
 * This class represents the Collector document that will be stored in MongoDB.
 * It includes details such as the collector's ID, associated bin, driver information, and collection date.
 */
@Setter
@Getter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "Collector_Details")
public class Collector {

    /**
     * Unique identifier for each collector document (automatically generated by MongoDB).
     */
    @Id
    private String id;

    /**
     * Unique collector identifier.
     * Indexed to ensure that each collector has a unique identifier.
     */
    @Indexed(unique = true)
    private String collectorId;  // Changed 'CollectorId' to 'collectorId' to follow camelCase naming.

    /**
     * The ID of the user associated with this collection.
     */
    private String userId;  // Changed 'userId' to follow camelCase.

    /**
     * The ID of the bin associated with this collection.
     */
    private String binId;

    /**
     * The type of the bin being collected (e.g., recycling, general waste).
     */
    private String binType;  // Changed 'binType' to follow camelCase.

    /**
     * The ID of the driver assigned to this collection.
     */
    private String driverId;  // Changed 'DriverId' to 'driverId' for camelCase consistency.

    /**
     * The name of the driver assigned to this collection.
     */
    private String driverName;  // Changed 'DriverName' to 'driverName' for camelCase consistency.

    /**
     * The date when the bin collection occurred.
     */
    private Date collectionDate;  // Changed 'CollectionDate' to 'collectionDate' for camelCase consistency.
}
