package edu.sliit.document;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

/**
 * This class represents the Payment document that will be stored in MongoDB.
 * It includes details such as payment ID, user ID, payment amount, and payment dates.
 */
@Setter
@Getter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "Payment_Details")  // Fixed typo: 'collation' → 'collection'
public class Payment {

    /**
     * Unique identifier for each payment document (automatically generated by MongoDB).
     */
    @Id
    private String id;

    /**
     * Unique payment identifier.
     * Indexed to ensure each payment has a unique ID.
     */
    @Indexed(unique = true)
    private String paymentId;  // Changed 'PaymentId' to 'paymentId' to follow Java naming conventions (camelCase).

    /**
     * The ID of the user who made the payment.
     */
    private String userId;  // Changed 'UserId' to 'userId' to follow camelCase.

    /**
     * The amount of the payment.
     */
    private Number paymentAmount;  // Changed 'PaymentAmount' to 'paymentAmount' for camelCase consistency.

    /**
     * The date when the payment was made.
     */
    private Date paymentDate;  // Changed 'PaymentDate' to 'paymentDate' for camelCase consistency.

    /**
     * The date for the next scheduled payment.
     */
    private Date nextPaymentDate;  // Changed 'NextPaymentDate' to 'nextPaymentDate' for camelCase consistency.
}
