package edu.sliit.document;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * This class represents the User document that will be stored in MongoDB.
 * It contains details such as user ID, email, password, personal details, and status.
 */
@Setter
@Getter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "User_Details")  // Fixed typo: 'collation' → 'collection'
public class User {

    /**
     * Unique identifier for each user document (automatically generated by MongoDB).
     */
    @Id
    private String id;

    /**
     * Unique user identifier.
     * Indexed to ensure that each user has a unique user ID.
     */
    @Indexed(unique = true)
    private String userId;  // Changed 'UserId' to 'userId' to follow Java naming conventions (camelCase).

    /**
     * The email address of the user.
     */
    private String email;

    /**
     * The password of the user.
     */
    private String password;

    /**
     * The first name of the user.
     */
    private String firstName;

    /**
     * The last name of the user.
     */
    private String lastName;

    /**
     * The username of the user.
     */
    private String username;

    /**
     * The location of the user.
     */
    private String location;

    /**
     * The current status of the user (e.g., active, inactive).
     */
    private String status;

    /**
     * The points associated with the user (e.g., for a reward system).
     */
    private Number points;
}
